import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
const db=new PGlite();
const a='00000000-0000-4000-8000-000000000001',b='00000000-0000-4000-8000-000000000002',c='00000000-0000-4000-8000-000000000003',u='00000000-0000-4000-8000-000000000004';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz,raw_user_meta_data jsonb default '{}');create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;`);
for(const [id,email,confirmed] of [[a,'a@example.com',true],[b,'b@example.com',true],[c,'c@example.com',true],[u,'u@example.com',false]])await db.query('insert into auth.users(id,email,email_confirmed_at) values($1,$2,$3)',[id,email,confirmed?'2026-10-03T00:00:00Z':null]);
const sql=await readFile(new URL('../supabase/migrations/001_wallet.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
async function actor(id){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');}
await actor(u);await assert.rejects(()=>db.query('select public.wallet_dashboard()'),/verified/);
await actor(a);const gid=(await db.query("select public.wallet_create_group('Dinner crew') as id")).rows[0].id;
assert.equal((await db.query('select public.wallet_dashboard() as data')).rows[0].data.groups.length,1);
await assert.rejects(()=>db.query('select * from wallet_private.groups'),/permission denied/);
await db.query('select public.wallet_invite($1,$2)',[gid,' B@example.com ']);
await actor(c);assert.equal((await db.query('select public.wallet_dashboard() as data')).rows[0].data.groups.length,0);await assert.rejects(()=>db.query('select public.wallet_group($1)',[gid]),/access/);
await actor(b);const invite=(await db.query('select public.wallet_dashboard() as data')).rows[0].data.invitations[0].id;
await actor(c);await assert.rejects(()=>db.query('select public.wallet_accept_invite($1)',[invite]),/another email/);
await actor(b);await db.query('select public.wallet_accept_invite($1)',[invite]);
await assert.rejects(()=>db.query('select public.wallet_invite($1,$2)',[gid,'c@example.com']),/access/);
const eid='00000000-0000-4000-8000-000000000011';
const args=[gid,eid,'Dinner',90000,a,'2026-10-03',JSON.stringify([{user_id:a,amount:45000},{user_id:b,amount:45000}])];
await db.query('select public.wallet_add_expense($1,$2,$3,$4,$5,$6,$7)',args);
await db.query('select public.wallet_add_expense($1,$2,$3,$4,$5,$6,$7)',args);
let snapshot=(await db.query('select public.wallet_group($1) as data',[gid])).rows[0].data;
assert.equal(snapshot.expenses.length,1);assert.equal(snapshot.expenses[0].created_by,b);assert.equal(snapshot.shares.length,2);
await assert.rejects(()=>db.query('select public.wallet_add_expense($1,$2,$3,$4,$5,$6,$7)',[...args.slice(0,3),90001,...args.slice(4)]),/add up/);
const badId='00000000-0000-4000-8000-000000000012';
await assert.rejects(()=>db.query('select public.wallet_add_expense($1,$2,$3,$4,$5,$6,$7)',[gid,badId,'Bad',100,a,'2026-10-03',JSON.stringify([{user_id:c,amount:100}])]),/group members/);
await assert.rejects(()=>db.query('select public.wallet_add_expense($1,$2,$3,$4,$5,$6,$7)',[gid,badId,'Bad',100,a,'2026-10-03',JSON.stringify([{user_id:a,amount:50},{user_id:a,amount:50}])]),/twice/);
assert.equal((await db.query('select public.wallet_group($1) as data',[gid])).rows[0].data.expenses.length,1);
const sid='00000000-0000-4000-8000-000000000021';
await db.query('select public.wallet_settle($1,$2,$3,$4,$5)',[gid,sid,b,a,10000]);await db.query('select public.wallet_settle($1,$2,$3,$4,$5)',[gid,sid,b,a,10000]);
assert.equal((await db.query('select public.wallet_group($1) as data',[gid])).rows[0].data.settlements.length,1);
await assert.rejects(()=>db.query('select public.wallet_settle($1,$2,$3,$4,$5)',[gid,badId,a,a,100]),/repayment/);
await db.exec('reset role;set role anon');await assert.rejects(()=>db.query('select public.wallet_dashboard()'),/permission denied/);
console.log('PASS: repeatable migration; verified-email requirement; group privacy; invitation ownership; admin permissions; member expense creation; exact shares; invalid-save rollback; retry deduplication; repayments; anonymous denial.');
await db.exec('reset role');
await db.query('delete from wallet_private.shares where expense_id=$1',[eid]);await db.query('insert into wallet_private.shares(expense_id,user_id,amount) values($1,$2,90000)',[eid,b]);
const update=await readFile(new URL('../supabase/migrations/002_everyone_splits.sql',import.meta.url),'utf8');await db.exec(update);await db.exec(update);
await actor(a);
const oldData=(await db.query('select public.wallet_group($1) as data',[gid])).rows[0].data;
assert.equal(oldData.shares.length,2);assert.deepEqual(oldData.shares.map(s=>s.amount),[45000,45000]);
const trip=(await db.query("select public.wallet_create_group('Whole group trip') as id")).rows[0].id;
const dinner='00000000-0000-4000-8000-000000000031',lunch='00000000-0000-4000-8000-000000000032';
await db.query('select public.wallet_add_shared_expense($1,$2,$3,$4,$5,$6,$7,$8)',[trip,dinner,'Dinner',47000,a,'2026-10-02','[]','everyone']);
await assert.rejects(()=>db.query('select public.wallet_add_shared_expense($1,$2,$3,$4,$5,$6,$7,$8)',[trip,'00000000-0000-4000-8000-000000000033','Personal',9900,a,'2026-10-02','[]','selected']),/shared equally/);
await db.query('select public.wallet_invite($1,$2)',[trip,'b@example.com']);await actor(b);
const nextInvite=(await db.query('select public.wallet_dashboard() as data')).rows[0].data.invitations.find(i=>i.group_name==='Whole group trip').id;
await db.query('select public.wallet_accept_invite($1)',[nextInvite]);
await db.query('select public.wallet_add_shared_expense($1,$2,$3,$4,$5,$6,$7,$8)',[trip,lunch,'Lunch',60000,b,'2026-10-03','[]','everyone']);
const shared=(await db.query('select public.wallet_group($1) as data',[trip])).rows[0].data;
assert.deepEqual(shared.shares.filter(s=>s.expense_id===dinner).map(s=>s.amount),[23500,23500]);
const net={};for(const e of shared.expenses)net[e.paid_by]=(net[e.paid_by]||0)+e.amount;for(const sh of shared.shares)net[sh.user_id]=(net[sh.user_id]||0)-sh.amount;
assert.equal(net[a],-6500);assert.equal(net[b],6500);
await assert.rejects(()=>db.query('select public.wallet_add_expense($1,$2,$3,$4,$5,$6,$7)',[trip,dinner,'Dinner',47000,a,'2026-10-02','[]']),/permission denied/);
await actor(a);
await db.query('select public.wallet_add_shared_expense($1,$2,$3,$4,$5,$6,$7,$8)',[trip,dinner,'Dinner',47000,a,'2026-10-02','[]','everyone']);
assert.equal((await db.query('select public.wallet_group($1) as data',[trip])).rows[0].data.expenses.length,2);
console.log('PASS: migration re-splits legacy expenses; late joining re-splits every group expense; 470/600 example leaves 65; selected splits rejected; old write endpoint blocked; retry after joining deduplicated.');
await db.close();
